import streamlit as st 

st.subheader("Follow policies set by Saudi Arabia's General Authority of Audiovisual Media and General Authority for Radio and Television to create a subsidiary company in compliance with media production rules and standards:")
st.write("")
st.write("- Obtaining necessary licenses: The company must obtain the necessary licenses from the General Authority of Audiovisual Media before commencing media production, including licensing the company and the products, programs, and services it offers.")
st.write("- Complying with laws and regulations: The company must comply with the laws and regulations specified by the General Authority of Audiovisual Media to ensure the organization of media production in the Kingdom and maintain a high level of quality and credibility.")
st.write("- Respecting ethical and cultural principles: The company must respect the ethical principles and cultural and religious values of Saudi society and avoid broadcasting any content that conflicts with these principles and values.")
st.write("- Prioritizing production quality: The company must work to achieve high quality media production and provide qualified equipment, human resources, and machinery to ensure this.")
st.write("- Providing financial reports: The company must provide financial and accounting reports regularly to the General Authority of Audiovisual Media to determine the company's financial commitment and levels of quality and productivity.")
st.write("- Complying with technical standards: The company must comply with the technical standards set by the General Authority of Audiovisual Media to achieve the highest level of quality and productivity in media production.")
st.write("- Providing protection for children: The company must provide sufficient protection for children and limit exposure to inappropriate content to protect children from harmful and dangerous content.")
st.write("- Maintaining credibility and neutrality: The company must maintain credibility and neutrality in media production, avoid bias and prejudice, and present information in a fair and accurate manner to ensure the credibility of the content and maintain the company's reputation.")
st.write("- Providing services at the highest level: The company must provide services at the highest level of quality and achieve customer satisfaction to ensure the company's continuity and sustainable profits.")
st.write("- Communicating and collaborating with the authority: The company must communicate and collaborate continuously with the General Authority of Audiovisual Media, receive feedback, guidance, and proposals from it, to improve the company's performance and achieve desired goals.")
st.write("- Adhering to standards and principles of transparency and integrity in all financial and administrative operations.")
st.write("- Applying high-quality standards in producing programs and media content, achieving discipline and accuracy in work.")
st.write("- The company's commitment to the General Authority for Radio and Television's directives regarding the content and programs produced by the company.")
st.write("- Providing a healthy and safe work environment for employees and workers in the company, and respecting the rights of workers in it.")
st.write("- Adhering to principles of protecting intellectual property rights and copyright and ensuring that the intellectual property rights of others are not violated in the production of programs and media content.")
st.write("- The company's commitment to compliance with laws and regulations related to journalism and media and ensuring that the laws of the Kingdom of Saudi Arabia in this field are not violated.")
st.write("- Providing the necessary information and data to the General Authority for Radio and Television upon request and cooperating with it in the necessary review and monitoring procedures.")
st.write("- Achieving principles of sustainability and environmental preservation in all company activities and working to reduce negative impacts on the environment.")
st.write("- Encouraging innovation and development in producing programs and media content and employing modern technologies in work.")
st.write("- Adhering to the necessary securityand safety standards in all activities and operations related to the production of programs and media content, and ensuring the safety of equipment and devices used in work.")
st.write("")