import streamlit as st 

st.subheader("When creating a subsidiary company of the General Authority for Radio and Television and General Authority for Audiovisuain the Kingdom of Saudi Arabia, it must adhere to several standards, including:")
st.write("")
st.write("- Obtaining necessary licenses: The company must obtain the necessary licenses from the General Authority for Audiovisual Media before commencing media production. This includes licensing the company, its products, programs, and services.")
st.write("- Compliance with laws and regulations: The company must comply with the laws and regulations specified by the General Authority for Audiovisual Media to regulate the media production process in the kingdom and maintain a high level of quality and credibility.")
st.write("- Respect for ethical and cultural principles: The company must respect the ethical principles and cultural and religious values of the Saudi community and avoid broadcasting any content that contradicts these principles and values.")
st.write("- Focus on production quality: The company must work to achieve high-quality media production and provide qualified personnel, equipment, and devices to ensure this.")
st.write("- Financial reporting: The company must regularly submit financial and accounting reports to the General Authority for Audiovisual Media to determine the company's financial commitment level, quality, and productivity.")
st.write("- Compliance with technical standards: The company must comply with the technical and artistic standards specified by the General Authority for Audiovisual Media to achieve the highest level of quality and productivity in media production.")
st.write("- Child protection: The company must provide sufficient protection for children and limit the exposure of inappropriate content to them to protect them from harmful and dangerous content.")
st.write("- Commitment to credibility and neutrality: The company must maintain credibility and neutrality in media production, avoid bias and prejudice, present information fairly and accurately, to ensure content credibility and maintain the company's reputation.")
st.write("- Providing services at the highest level: The company must provide services at the highest level of quality to achieve customer satisfaction, ensure the company's continuity, and achieve sustainable profits.")
st.write("- Communication and cooperation with the authority: The company must maintain continuous communication and cooperation with the General Authority for Audiovisual Media, receive feedback, guidance, and suggestions from it to improve the company's performance and achieve the desired goals.")
st.write("- The company's commitment to the regulations and rules specified by the General Authority for Radio and Television in the Kingdom of Saudi Arabia.")
st.write("- Adherence to high-quality standards in producing programs and media content, ensuring accuracy and discipline in the work.")
st.write("- Applying standards of transparency and integrity in all financial and administrative operations.")
st.write("- The company's commitment to protecting intellectual property rights and copyright and not violating them in the production of programs and media content.")
st.write("- The company's commitment to media ethics and not publishing or producing any content that violates the laws and regulations in force in the Kingdom of Saudi Arabia.")
st.write("- The company's commitment to environmental preservation and sustainability in all its activities and working to reduce negative impacts on the environment.")
st.write("- Conducting regular reviews and necessary reports to ensure that the company follows the specified standards and complies with the regulations and rules in force.")
st.write("- Providing a safe and healthy work environment for employees and workers in the company and adhering to safety and security standards in all operations and activities related to the production of programs and media content.")
st.write("- Achieving principles of innovation and development in producing programs and media content and employing modern technologies in work.")
st.write("- Providing the necessary support and training for employees and workers in the company to improve their skills and develop their capabilities.")
st.write("- The company's commitment to providing sufficient financialand human resources to produce high-quality programs and media content and ensure the continuity of the company's work.")
st.write("- The company's commitment to maintaining the reputation of the company and the General Authority for Radio and Television and not taking any actions that conflict with public interests.")
st.write("-  Cooperating with the General Authority for Radio and Television in achieving its goals and efforts in providing high-quality media services to the public and the community.")